### PR TITLE
fix: style clashing with dark mode root element

### LINKED ISSUE #106: Radix and Puck styles clashing
Various issues occur when using Radix with Puck resulting in illegible text.

See below screenshot from FF on MacOS, running dark mode and Radix using system theme.

image

Reported by @gothfemme in Discord.

### PR DESCRIPTION
**Pull request by gothfemme**
- Adds in styles so Puck doesn't inherit styles from the document body. 
- Fixes an issue where the preview root would inherit/be blocked by the editor frame. 
  - I'm just faking the frame with a box shadow.
- Fixes an issue where horizontal scrollbars were always visible for `SidebarSection`'s even when not overflowing.
- Closes #106

### CODE REVIEW

**Comment by gothfemme** [comment]
I kept the styles in `Puck/index.tsx` as inline rather than creating a new file for it as I imagine that's outside the scope of this ticket

File: packages/core/components/Puck/index.tsx [hunk 1]
```diff
@@ -410,8 +411,8 @@ export function Puck({
                     <div
                       className="puck-root"
                       style={{
-                        background: "white",
                         border: "1px solid var(--puck-color-grey-8)",
+                        boxShadow: "0px 0px 0px 32px var(--puck-color-grey-10)",
```
Comment (chrisvxd) [inline packages/core/components/Puck/index.tsx:415]: Not sure I understand the reason for this change? Can you share a screenshot of the original issue?

This fix causes and additional white border in Safari and Chrome due to the zoom factor (FF doesn't respect zoom per #15)

image

File: packages/core/components/SidebarSection/styles.module.css [hunk 2]
```diff
@@ -12,7 +13,7 @@
   background: white;
   padding: 16px;
   border-bottom: 1px solid var(--puck-color-grey-8);
-  overflow-x: scroll;
+  overflow-x: auto;
```
Comment (chrisvxd) [inline packages/core/components/SidebarSection/styles.module.css:16]: Can you split this fix into a separate commit for our changelogs?

```
fix: only show sidebar scroll bars if necessary
```

**Review by chrisvxd — CHANGES_REQUESTED** [review]
Excellent stuff @gothfemme! Left a couple of comments.

Updating the inline styles is definitely the right place for now. These really need to get pulled out at some point.

File: packages/core/components/SidebarSection/styles.module.css (hunk 2 above)
Comment (gothfemme) [reply packages/core/components/SidebarSection/styles.module.css:16]: yeah, can do.

File: packages/core/components/Puck/index.tsx (hunk 1 above)
Comment (gothfemme) [reply packages/core/components/Puck/index.tsx:415]: Ah yeah, it definitely isn't the ideal solution. Reason was setting background on the frame would cause the preview root to either:
1. Inherit from the frame if set to inherit
2. If no BG is set on preview root, the frame BG is all that would show rather than the background for the document body

image
The example here being the 2nd case with the frame BG taking over.

This was my primary reason for asking about portals in #106. I could also imagine a fix involving pseudo-elements, though would need to move some styles out of inline styles.

**Review by chrisvxd — APPROVED** [review]
Perfect 🚀
