### PR TITLE
fix: updating root component Id using populateIds

### LINKED ISSUE #1221: Using `defaultProps` for slots at the root level results in error
## Description

Slots defined in the [root config](https://puckeditor.com/docs/api-reference/configuration/config#root) break when `defaultProps` is used to provide nested components.

This issue occurs because `defaultProps` in the root config does not automatically generate IDs for slot components, unlike when used in component configs.

## Environment

- Puck version: 0.19.3

## Steps to reproduce

1. Render Puck with the following config that uses slots with default props at the root level, without setting component IDs for nested content:

```tsx
export const config: Config<Props> = {
  components: {
    Heading: {
      fields: {
        title: { type: "text" },
      },
      render: ({ title }) => <Heading title={title} />,
    },
  },
  root: {
    fields: {
      content: { type: "slot" },
      object: { type: "object", objectFields: { content: { type: "slot" } } },
      array: {
        type: "array",
        arrayFields: { content: { type: "slot" } },
      },
    },
    defaultProps: {
      content: [
        {
          type: "Heading",
          // Does not set an ID
          props: { title: "Hello from the root" },
        },
      ],
      object: {
        content: [
          {
            type: "Heading",
            // Does not set an ID
            props: { title: "Hello from the root" },
          },
        ],
      },
      array: [
        {
          content: [
            {
              type: "Heading",
              // Does not set an ID
              props: { title: "Hello from the root" },
            },
          ],
        },
      ],
    },
    render: ({ children, slot: Content, object: { content: ObjectContent }, array }) => {
      return (
        <div>
          <h2>Default content:</h2>
          {children}
          <hr />
          <h2>Non nested content:</h2>
          <Content />
          <hr />
          <h2>Object nested content: </h2>
          <ObjectContent />
          <hr />
          <h2>Array nested content: </h2>
          {array.map(({ content: ArrayContent }, index) => (
            <ArrayContent key={index} />
          ))}
        </div>
      );
    },
  },
};
```

2. Navigate to the editor

## What happens

The editor throws an error:
```bash
Each child in a list should have a unique "key" prop.

Check the render method of `ul`. It was passed a child from LayerTree. See https://react.dev/link/warning-keys for more information.
```

*This does not occur when IDs are explicitly provided for the nested components.*

## What I expect to happen

Slot fields in the root config should behave the same as in component configs. If default slot content is provided, it should be rendered and used without having to manually generate IDs.

## Additional Media

https://github.com/user-attachments/assets/7fbc9efe-bd41-4cee-96d9-4c0697166b5f

### PR DESCRIPTION
**Pull request by xaviemirmon**
fixes #1221 

Supercedes #1303 

Updating root component ids with `populateIds` helper function to avoid touching `walk-app-state`.

### CODE REVIEW

File: packages/core/components/Puck/index.tsx [hunk 1]
```diff
@@ -230,6 +254,8 @@ function PuckProvider<
       ...rootProps,
     };
 
+    updateIds(defaultedRootProps, config);
```
Comment (chrisvxd) [inline packages/core/components/Puck/index.tsx]: Can we not just use `populateIds` here? It's recursive so should handle everything you've implemented in `updateIds`

```ts
const root = populateIds(
  toComponent({ ...initialData?.root, props: defaultedRootProps }),
  config
)
```

Comment (xaviemirmon) [reply packages/core/components/Puck/index.tsx]: Oh cool I didn't know about the toComponent helper!
